runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /contact
  static_files: contact.html
  upload: contact\.html

- url: /login
  static_files: login.html
  upload: login\.html

- url: /loggedIn
  static_files: loggedIn.html
  upload: loggedIn\.html

- url: /.*
  script: app.app

# - url: /tasks/create_games
#   login: admin
# [END handlers]

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'gae-template-1725f'

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
